using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace CRUP_App.Entities
{
    public partial class User
    {
        [Key] // Specifies that this property is the primary key
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Specifies that this property is auto-generated by the database
        public int Id { get; set; }

        public string FirstName { get; set; } 

        public string LastName { get; set; } 

        public string Username { get; set; } = null!;

    
        public string Password { get; set; } = null!;

        public DateTime EnrollmentDate { get; set; }

        // Navigation property representing the collection of orders associated with the user
        public ICollection<Order>? Orders { get; set; }


    }
}